id: IA26601AD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T16:33:35+00:00'
last_modified: '2022-06-08T17:04:41.321249+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17646
  title: 'པྲ་སྒྲུབ་དང་པྲ་དཔྱད་ཕྱོགས་བསྒྲིགས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E118:
      image_group_id: I2PD19253
      title: ''
      total_pages: 84
      order: 1
      base_file: E118.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
