id: P010725
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD17646
  title: 'པྲ་སྒྲུབ་དང་པྲ་དཔྱད་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    e7b0c5f6ea5b4a9b9cdb602fdfde649f:
      image_group_id: I2PD19253
      title: ''
      volume_number: 1
      total_pages: 84
      base_file: v001.txt
